version: "2.2"

services:
   elastic:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
     environment:
       - discovery.type=single-node
     network_mode: host
   flask-server:
     build: .
     command: ./start.sh
     network_mode: host
     depends_on:
       elastic:
         condition: service_started
